volumes:
  postgres-dev-data:
  postgres-test-data:

networks:
  app-network:
    driver: bridge

services:
  app:
    container_name: javadev
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in db container
        POSTGRES_USER: atsd
        POSTGRES_PASSWORD: atsd
        POSTGRES_DEV_DB: atsd
        POSTGRES_TEST_DB: atsd_test
        POSTGRES_HOSTNAME: postgres-dev
        POSTGRES_TEST_HOSTNAME: postgres-test

#    volumes:
#      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    #network_mode: service:db-dev
    networks:
      - app-network
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  postgres-dev:
    container_name: postgres-dev
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      POSTGRES_PASSWORD: atsd
      POSTGRES_USER: atsd
      POSTGRES_DB: atsd

    networks:
      - app-network

  postgres-test:
    container_name: postgres-test
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: atsd
      POSTGRES_USER: atsd
      POSTGRES_DB: atsd_test

    networks:
      - app-network
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)